config/routes.rb
Trivote::Application.routes.draw do
  resources :itemgroups do
    resources :items do
      member do
        post :vote_up
        post :vote_down
      end
    end
  end

  devise_for :users

  authenticated :user do
    root to: 'itemgroups#index'
  end
  root :to => 'high_voltage/pages#show', :id => 'home'

end

app/models/itemgroup.rb
class Itemgroup < ActiveRecord::Base
  attr_accessible :name
  has_many :items
end

app/controllers/itemgroups_controller.rb
class ItemgroupsController < ApplicationController
  before_filter :authenticate_user!

  # GET /itemgroups
  # GET /itemgroups.json
  def index
    @itemgroups = Itemgroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @itemgroups }
    end
  end

  # GET /itemgroups/1
  # GET /itemgroups/1.json
  def show
    @itemgroup = Itemgroup.find(params[:id])
    @items = Item.plusminus_tally.where('itemgroup_id = ?', @itemgroup.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @itemgroup }
    end
  end

  # GET /itemgroups/new
  # GET /itemgroups/new.json
  def new
    @itemgroup = Itemgroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @itemgroup }
    end
  end

  # GET /itemgroups/1/edit
  def edit
    @itemgroup = Itemgroup.find(params[:id])
  end

  # POST /itemgroups
  # POST /itemgroups.json
  def create
    @itemgroup = Itemgroup.new(params[:itemgroup])

    respond_to do |format|
      if @itemgroup.save
        format.html { redirect_to @itemgroup, notice: 'Itemgroup was successfully created.' }
        format.json { render json: @itemgroup, status: :created, location: @itemgroup }
      else
        format.html { render action: "new" }
        format.json { render json: @itemgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /itemgroups/1
  # PUT /itemgroups/1.json
  def update
    @itemgroup = Itemgroup.find(params[:id])

    respond_to do |format|
      if @itemgroup.update_attributes(params[:itemgroup])
        format.html { redirect_to @itemgroup, notice: 'Itemgroup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @itemgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itemgroups/1
  # DELETE /itemgroups/1.json
  def destroy
    @itemgroup = Itemgroup.find(params[:id])
    @itemgroup.destroy

    respond_to do |format|
      format.html { redirect_to itemgroups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/itemgroups_helper.rb
module ItemgroupsHelper
end

app/views/itemgroups/_form.html.erb
<%= form_for(@itemgroup) do |f| %>
  <% if @itemgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@itemgroup.errors.count, "error") %> prohibited this itemgroup from being saved:</h2>

      <ul>
      <% @itemgroup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/itemgroups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @itemgroup %> |
<%= link_to 'Back', itemgroups_path %>

app/views/itemgroups/index.html.erb
<p id="notice"><%= notice %></p>

<ul class="nav nav-tabs nav-stacked">
  <% @itemgroups.each do |itemgroup| %>
  <li><%= link_to itemgroup.name, itemgroup %></li>
  <% end %>
</ul>

<br />

<%= link_to 'New group', new_itemgroup_path %>

app/views/itemgroups/new.html.erb
<h4>New group</h4>

<%= render 'form' %>

<%= link_to 'Back', itemgroups_path %>

app/views/itemgroups/show.html.erb
<p id="notice"><%= notice %></p>

<div class="well">
  <h4><%= @itemgroup.name %></h4>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Added by</th>
      <th>Ranking</th>
      <th>Votes</th>
      <th colspan="2"></th>
    </tr>
    </thead>
    <tbody>

    <% @items.each do |item| %>
        <tr>
          <td><%= link_to_unless item.url.empty?, item.name, item.url, :target => "_blank" %></td>
          <td><%= item.description %></td>
          <td><%= item.user.email %></td>
          <td><%= item.plusminus %></td>
          <td><%= item.votes_count %></td>
          <% unless current_user.voted_on?(item) %>
              <td style="width: 25px;">
                <%= button_to('+1', vote_up_itemgroup_item_path(@itemgroup, item), :class => "btn btn-mini btn-success", :form_class => "form-inline form-vote") %>
              </td>
              <td style="width: 25px;">
                <%= button_to('-1', vote_down_itemgroup_item_path(@itemgroup, item), :class => "btn btn-mini btn-danger", :form_class => "form-inline form-vote") %>
              </td>
          <% else %>
              <td style="width: 25px;"></td>
              <td style="width: 25px;"></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br/>

<%= link_to 'New Item', new_itemgroup_item_path(@itemgroup) %>