config/routes.rb
Trivote::Application.routes.draw do
  resources :itemgroups do
    resources :items do
      member do
        post :vote_up
        post :vote_down
      end
    end
  end

  devise_for :users

  authenticated :user do
    root to: 'itemgroups#index'
  end
  root :to => 'high_voltage/pages#show', :id => 'home'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :itemgroup

  attr_accessible :archived, :name, :url, :description, :itemgroup_id

  acts_as_voteable

  validates :name, :presence => true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!

  # GET /items
  # GET /items.json
  def index
    @items = Item.plusminus_tally

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @itemgroup = Itemgroup.find(params[:itemgroup_id])
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @itemgroup = Itemgroup.find(params[:itemgroup_id])
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @itemgroup = Itemgroup.find(params[:itemgroup_id])
    @item = Item.new(params[:item])
    @item.user = current_user

    respond_to do |format|
      if @item.save
        Statsd.increment("trivote.#{Rails.env}.items.create")
        format.html { redirect_to itemgroup_url(@item.itemgroup_id), notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  def vote_up
    begin
      current_user.vote_for(@item = Item.find(params[:id]))
      Statsd.increment("trivote.#{Rails.env}.votes.upvote")
      redirect_to itemgroup_url(params[:itemgroup_id])
    rescue ActiveRecord::RecordInvalid
      redirect_to itemgroup_url(params[:itemgroup_id])
    end
  end

  def vote_down
    begin
      current_user.vote_against(@item = Item.find(params[:id]))
      Statsd.increment("trivote.#{Rails.env}.votes.downvote")
      redirect_to itemgroup_url(params[:itemgroup_id])
    rescue ActiveRecord::RecordInvalid
      redirect_to itemgroup_url(params[:itemgroup_id])
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for [@itemgroup, @item] do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :cols => "30", :rows => "10" %>
  </div>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :itemgroup_id, "Group" %>
    <%= f.select "itemgroup_id", Itemgroup.all.collect{|t|[t.name,t.id]}, :selected => params[:itemgroup_id] %>
  </div>
  <!-- <div class="field">
    <%= f.label :archived %>
    <%= f.check_box :archived %>
  </div> -->
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Back', itemgroup_items_path(params['itemgroup_id']) %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Added by</th>
    <th colspan="3">Votes</th>
  </tr>
  </thead>
  <tbody>

  <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.name, item.url, :target => "_blank" %></td>
        <td><%= item.description %></td>
        <td><%= item.user.email %></td>
        <td><%= item.plusminus %></td>
        <% unless current_user.voted_on?(item) %>
        <td style="width: 25px;">
          <%= button_to('+1', vote_up_item_path(item), :class => "btn btn-mini btn-success", :form_class => "form-inline form-vote") %>
        </td>
        <td style="width: 25px;">
          <%= button_to('-1', vote_down_item_path(item), :class => "btn btn-mini btn-danger", :form_class => "form-inline form-vote") %>
        </td>
        <% else %>
          <td style="width: 25px;"></td>
          <td style="width: 25px;"></td>
        <% end %>
        <!-- <td><%= link_to 'Show', item %> <%= link_to 'Edit', edit_item_path(item) %> <%= link_to 'Destroy', item, confirm: 'Are you sure?', method: :delete %></td> -->
      </tr>
  <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', itemgroup_path(@itemgroup) %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Url:</b>
  <%= @item.url %>
</p>

<p>
  <b>Archived:</b>
  <%= @item.archived %>
</p>

<p>
  <b>Group:</b>
  <%= @item.itemgroup %>
</p>

<p>
  <b>User:</b>
  <%= @item.user %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>